name: Pipeline

env:
  IMAGE_NAME: tpick-crawler
  IMAGE_TAGS: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
  IMAGE_FULL_TAGS: ${{ env.IMAGE_TAGS }}:latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_FULL_TAGS }}
          cache-from: type=registry,ref=${{ env.IMAGE_FULL_TAGS }}
          cache-to: type=inline
