name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: TPick-VN/tpick-actions/docker@v1
        with: 
          image-name: tpick-crawler
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
